# Generated by Django 3.0.7 on 2020-07-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='images_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('images_pic', models.FileField(upload_to='')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
