# Generated by Django 3.0.7 on 2020-07-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images_log',
            name='images_pic',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
